[[_preinstall]]

== 安装准备 ==

该章节主要说明为了能顺利和快速安装Ambari以及HDP而对系统进行必要的设置，主要包含以下几个方面

=== 配置系统安装源

集群安装过程中，需要安装一些额外的软件和程序，如果集群环境不能访问互联网上的系统安装源(yum源)，那需要自己搭建yum源，并在每个节点上配置能访问到该源。

NOTE:: 建议使用Everthing ISO 来做本地源，而不是DVD ISO。这样能尽可能提供完整的软件包

=== 主机名配置

要确保所有的主机名都有唯一的名字，且不为 `localhost` ,最好主机名符合 FQDN 要求，即带有域名的方式
要保证 `hostname` 命令和 `hostname -f` 的输出保持一致。

然后在Ambari节点上把主机名和对应的IP地址写入到 `/etc/hosts` 文件中，确保能通过主机名可以访问到所有的节点，考虑到以后管理的方便，可以把FQDN以及主机名前缀都写入到 hosts 中，类似如下：

....
28.163.0.31    hadoop1.fzzq.com    hadoop1
28.163.0.32    hadoop2.fzzq.com    hadoop2
28.163.0.33    hadoop3.fzzq.com    hadoop3
28.163.0.34    hadoop4.fzzq.com    hadoop4
....


=== 最大文件打开数量

Ambari运行账号要求所能开的文件句柄数量在10000以上，请在每个节点上执行

[source,bash]
....
ulimit -Sn
ulimit -Hn
....

上述命令输出结果如果小于10000，请配置 `limits.conf` 文件，确保文件句柄数量满足要求。

=== 设置SSH无密码登陆

虽然Ambari支持用提供密码的方式管理集群，但是从便利方面考虑，还是建议配置Ambari到集群中所有节点的无密码登陆。配置步骤如下：

首先在Ambari节点上生成私钥和公钥，可以使用下面的命令：

 `ssh-keygen -t rsa -b 1024 -N '' -f $HOME/.ssh/id_rsa`

然后将Ambari节点上的公钥加入到所有节点的认证文件中，节点较多的情况下，可以使用如下脚本：

[source,bash]
....
#!/bin/bash
# setup password-less ssh login 

# node password,edit it according your cluster
export SSHPASS='your password'

#get sshpass
which sshpass 2>&1 >/dev/null || yum install -y -q sshpass

# get all fingprint 
grep -E -v '^127|:' /etc/hosts |grep -v '^$' |awk '{print $2}' |ssh-keyscan -4 -t rsa -f -  >>$HOME/.ssh/known_hosts
for host in $(grep -E -v '^127|:' /etc/hosts |grep -v '^$' |awk '{print $2}')
do
    sshpass -e ssh-copy-id root@${host}
    scp /etc/hosts root@${host}:/etc/
done
....

=== 安装必要的工具

为了后面的部署能同时操作集群所有节点，所有节点必须安装一些基本工具和便于运维的工具

[source,bash]
....
#!/bin/bash
# install necessary OpDevs utils
for host in $(grep -E -v '^127|:' /etc/hosts |grep -v '^$' |awk '{print $2}')
do
    ssh root@${host} "yum install -y pdsh rsync"
done
pdsh "yum install -y unzip bzip2 vim net-tools lsof ntp wget tar"
....

=== 启用NTP

所有节点必须配置NTP，并启动

[source,shell]
....
pdsh "systemctl start ntpd && systemctl enable ntpd"
....

=== 关闭防火墙，禁用SELinux

[source,bash]
....
pdsh "systemctl disable firewalld && systemctl stop firewalld"
pdsh "sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux"
pdsh "setenforce 0"
....

=== 安装Oracle JDK

首先从Oracle官方安装下载最新稳定版本的Oracle JDK，同时下载JCE文件。将文件上传到Ambari节点的/root目录下,然后利用下面的脚本安装到全部节点上

[source,bash]
....
pdcp jdk-8u181-linux-x64.rpm jce_policy-8.zip /root/
pdsh "rpm -ivh /root/jdk-8u181-linux-x64.rpm"
pdsh "unzip -j -q -d /usr/java/jdk1.8.0_181-amd64/jre/lib/security/ jce_policy-8.zip"
....

=== 配置本地源

从官方网站源直接安装会非常慢，因此首先需要从官方离线安装包，并配置成yum源。


首先安装必要的工具

[source,bash]
....
yum install -y yum-utils createrepo  nginx
....

从官方下载对应的离线安装源，并解压到指定的目录

[source,bash]
....
cd /var/www/html
wget http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.1.0/ambari-2.7.1.0-centos7.tar.gz
wget http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/HDP-3.0.1.0-centos7-rpm.tar.gz
wget http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.22/repos/centos7/HDP-UTILS-1.1.0.22-centos7.tar.gz
wget http://public-repo-1.hortonworks.com/HDP-GPL/centos7/3.x/updates/3.0.1.0/HDP-GPL-3.0.1.0-centos7-gpl.tar.gz
mkdir hdp3.0
cd hdp3.0
tar -xzf ../*.tar.gz
....

配置nginx，使得所有节点可以访问本地源

[source]
....
server {
listen 80;
server_name hdp.fzzq.com;
root /var/www/html/hdp3.0;
audoindex on
}
....

配置好后的各仓库访问路径如下：

.本地安装源一览表
|===
| 仓库名称      |       地址        
| Ambari       | <http://hdp.fzzq.com/ambari/centos7/2.7.1.0-169/>
| HDP Base     | <http://hdp.fzzq.com/HDP/centos7/3.0.1.0-187/>
| HDP-UTILS    | <http://hdp.fzzq.com/HDP-UTILS/centos7/1.1.0.22/>
| HDP-GPL Base URL | <http://hdp.fzzq.com/HDP-GPL/centos7/3.0.1.0-187/>
|===






