[[shell]]
= HBase Shell 基本命令 =

HBase Shell 是一个 link:http://jruby.org[(J)Ruby] 的IRB程序，内置了针对HBase的命令。

要运行HBase shell，在安装有HBase的服务器上，切换到 `hbase` 账号，执行下面的命令即可：

[source,bash]
----
$ hbase shell
----

打 `help`  并按回车键，可以看到一系列的命令以及命令选项。在 Shell 里执行命令需要注意以下几点：

1. 所有名字，比如表名，列族名，列名都必须使用单引号进行引用，比如 'table1', 'cf1','cf1:col1'。
2. 创建和修改表的配置时使用的是Ruby Hashes，比如 `{'key1' => 'value1','key2' => 'value2', ...}` 。它需要用一对花括号('{}')表明整个对象的开始和结尾，每对key-value之间通过逗号分隔，key-value之间用 `=>` 关联。
3. 如果想输入二进制的数值，需要使用双引号("")进行引用，并且采取16进制表示，比如：
+
............................................................................
get 'table1', "key\x04\x05"
get 'table1', "key\002\005"
get 'table1', "key\xef\xba", 'cf1:', "\x02\04"
............................................................................

HBase Shell 基本命令可以大致分为以下几类：

- 表管理命令
- 数据操作命令
- 命名空间(namespace)相关命令
- 通用命令
- 授权命令

如果想了解某个详细的命令的细节，可以输入 `help '<command>'` ，比如想知道创建表的命令 `create` 的详细用法，可以这样查看

............................................................................
hbase(main):001:0> help 'create'
Creates a table. Pass a table name, and a set of column family
specifications (at least one), and, optionally, table configuration.
Column specification can be a simple string (name), or a dictionary
(dictionaries are described below in main help output), necessarily
including NAME attribute.
Examples:

Create a table with namespace=ns1 and table qualifier=t1
  hbase> create 'ns1:t1', {NAME => 'f1', VERSIONS => 5}

  ...

  hbase> create 't1', 'f1', {NUMREGIONS => 15, SPLITALGO => 'HexStringSplit'}
  hbase> create 't1', 'f1', {NUMREGIONS => 15, SPLITALGO => 'HexStringSplit', REGION_REPLICATION => 2, CONFIGURATION => {'hbase.hregion.scan.loadColumnFamiliesOnDemand' => 'true'}}

You can also keep around a reference to the created table:

  hbase> t1 = create 't1', 'f1'

Which gives you a reference to the table named 't1', on which you can then
call methods.

............................................................................

== 表管理命令 ==

NOTE: 可以在HBase Shell 中执行 `help 'ddl'` 来查看相关帮助

=== list ===

list 命令列出Hbase中的表，可以传递一个正则表达式的表名参数用于过滤输出，比如：

[source]
----
hbase> list
hbase> list 'abc.*'
hbase> list 'ns:abc.*'
hbase> list 'ns:.*'
----

=== create ===

创建一个表，传递表名以及至少一个列族，同时也可以在创建时设置表配置项以及列配置。

创建一个在命名空间为 `ns1` 的表，表限定符为 `t1`

`hbase> create 'ns1:t1', {NAME=> 'f1' ,VERSIONS => 5}`

在默认命名空间创建名为 `t1` 的表

............................................................................
  hbase> create 't1', {NAME => 'f1'}, {NAME => 'f2'}, {NAME => 'f3'}
  hbase> # 上述例子可以用下面的简单表达法实现:
  hbase> create 't1', 'f1', 'f2', 'f3'
  hbase> create 't1', {NAME => 'f1', VERSIONS => 1, TTL => 2592000, BLOCKCACHE => true}
  hbase> create 't1', {NAME => 'f1', CONFIGURATION => {'hbase.hstore.blockingStoreFiles' => '10'}}

............................................................................

表配置选项可以写在创建表的最后，比如：

............................................................................
hbase> create 'ns1:t1', 'f1', SPLITS => ['10', '20', '30', '40']
hbase> create 't1', 'f1', SPLITS => ['10', '20', '30', '40']
hbase> create 't1', 'f1', SPLITS_FILE => 'splits.txt', OWNER => 'johndoe'
hbase> create 't1', {NAME => 'f1', VERSIONS => 5}, METADATA => { 'mykey' => 'myvalue' }
hbase> # Optionally pre-split the table into NUMREGIONS, using
hbase> # SPLITALGO ("HexStringSplit", "UniformSplit" or classname)
hbase> create 't1', 'f1', {NUMREGIONS => 15, SPLITALGO => 'HexStringSplit'}
hbase> create 't1', 'f1', {NUMREGIONS => 15, SPLITALGO => 'HexStringSplit', REGION_REPLICATION => 2, CONFIGURATION => {'hbase.hregion.scan.loadColumnFamiliesOnDemand' => 'true'}}
............................................................................

还可以在创建表的同时“抓住”表句柄

`hbase> t1 = create 't', 'f1'`

之后，可以直接使用 `t1` 来引用该表

=== describe ===

Describe命令用来描述一个表的基本信息，比如：
............................................................................
hbase> describe 't1'
hbase> describe 'ns1:t1'
............................................................................

也可以使用 `desc` 缩写命令完成同样的功能

=== disable 和 disable_all ===

Disable命令用来禁止表，大部分情况下，当我们需要修改表的列族或者删除表时，需要先禁用表。
............................................................................
hbase> disable 't1'
hbase> disable 'ns1:t1'
............................................................................

如果我们想一次性禁用一批表，则可以使用 `disable_all` 这个高效命令，它接受正则表达式作为表参数。
............................................................................
hbase> disable_all 't.*'
hbase> disable_all 'ns:t.*'
hbase> disable_all 'ns:.*'
............................................................................

=== enable 和 enable_all ===

和 `disable` 命令相反， `enabled` 是启用表，两者语法类似。
............................................................................
hbase> enable 't1'
hbase> enable 'ns1:t1'
............................................................................


与此相对应的，也有一个一次性启用一批表的命令，`enabled_all` 也是接受正规表达式作为表参数

............................................................................
hbase> enable_all 't.*'
hbase> enable_all 'ns:t.*'
hbase> enable_all 'ns:.*'
............................................................................

=== drop 和 drop_all ===

Drop命令用来删除一个表，删除的表必须先用 `disable` 命令禁用
............................................................................
hbase> drop 't1'
hbase> drop 'ns1:t1'
............................................................................

同样的，如果想一次性删除一批表，则可以使用 `drop_all` 命令。
............................................................................
hbase> drop_all 't.*'
hbase> drop_all 'ns:t.*'
hbase> drop_all 'ns:.*'
............................................................................


=== exists ===

查看表是否存在
............................................................................
hbase> exists 't1'
hbase> exists 'ns1:t1'
............................................................................

=== is_disabled 和 is_enabled ===

`is_disabled` 和 `is_enabled` 分别用来判断表是否禁用或是否启动，其语法类似：

............................................................................
hbase> is_disabled 't1'
hbase> is_disabled 'ns1:t1'
hbase> is_enabled 't1'
hbase> is_enabled 'ns1:t1'
............................................................................


=== show_filter ===

`show_filter` 用来列出HBase中已有的过滤器。
............................................................................
hbase> show_filters

	ColumnPrefixFilter
	TimestampsFilter
	PageFilter
	...
	KeyOnlyFilter
............................................................................


=== alter ===

Alter用来修改表。如果 `hbase.online.schema.update.enable` 参数设置为False的话，则执行该命令之前必须禁用表。否则可以直接修改表。

表修改可能会导致表无法使用，因此建议修改现在测试环境测试通过后，然后在生产环境进行。

可以通过 `alter` 命令来增减、修改或删除列族，也可以修改表配置项。对列族的修改语法和 `create` 创建表时类似。列族规范可以是名字字符串，也可以是或带 `NAME` 属性的字典。

比如，为了修改表 `t1` 中的列族 `f1` 的最大单元最大版本(VERSIONS)为5，那么可以这么做：

`hbase> alter 't1', NAME => 'f1', VERSIONS => 5`

我们也可以同时修改好几个列族：

`hbase> alter 't1', 'f1', {NAME => 'f2', IN_MEMORY => true}, {NAME => 'f3', VERSIONS => 5}`

如果要删除一个列族，下面两个命令都可以完成

.....
hbase> alter 'ns1:t1', NAME => 'f1', METHOD => 'delete'
hbase> alter 'ns1:t1', 'delete' => 'f1'
.....

我们还可以改变表级属性，比如 `MAX_FILESIZE` , `READONLY` , `MEMSTORE_FLUSHSIZE` , `DURABILITY` 等。
比如我们想修改一个表的region最大大小为128MB，则可以执行下面的命令：

`hbase> alter 't1', MAX_FILESIZE => '134217728'`

我们可以通过设置表协处理器来给表增加一个协处理器：

`hbase> alter 't1',
    'coprocessor'=>'hdfs:///foo.jar|com.foo.FooRegionObserver|1001|arg1=1,arg2=2'`

同样的，我们还可以删除表级属性：
....
hbase> alter 't1', METHOD => 'table_att_unset', NAME => 'MAX_FILESIZE'
hbase> alter 't1', METHOD => 'table_att_unset', NAME => 'coprocessor$1'
....

可以在一个命令里对多个列族以及表的属性就行修改：
....
hbase> alter 't1', { NAME => 'f1', VERSIONS => 3 },
   { MAX_FILESIZE => '134217728' }, { METHOD => 'delete', NAME => 'f2' },
   OWNER => 'johndoe', METADATA => { 'mykey' => 'myvalue' }
....

=== alter_async 和 alter_status ===

`alter_async` 和 `alter` 语法相同,但是语义和 `alter` 略有不同。`alter_async` 指令可 以立即返回,而 `alter` 需要等到所有的region都更新完成后才会返回。而要查看更新期间所 有regions的更新进度, 可以使用 `alter_status` 命令。

== 数据操作命令 ==

数据操作命令可以通过 `help 'dml'` 来获得帮助。

=== count ===

count 命令用来统计一个表中的行数。该命令耗时很长(实际上是运行 `$HADOOP_HOME/bin/hadoop jar
hbase.jar rowcount` 命令，这会产生MR任务)，可以通过设置 CACHE 参数来增加每次获取的行数, 从而加速该命令的执行. 还可 以指定查询到多少行显示一次 count 结果, 默认值是1000行, 可以通过 INTERVAL 参数进行修改。

....
hbase> count 'ns1:t1'
hbase> count 't1'
hbase> count 't1', INTERVAL => 100000
hbase> count 't1', CACHE => 1000
hbase> count 't1', INTERVAL => 10, CACHE => 1000
....

=== delete ===

删除指定表以及列族和列的一个单元格，同时还可以指定时间戳。假设要删除表名为 `t1` ，行键为 `r1` 以及列为 `c1` ，且时间戳为 `ts1` 的单元格，那么可以执行下面任何一个操作：

....
hbase> delete 'ns1:t1', 'r1', 'c1', ts1
hbase> delete 't1', 'r1', 'c1', ts1
hbase> delete 't1', 'r1', 'c1', ts1, {VISIBILITY=>'PRIVATE|SECRET'}
....

=== deleteall ===

`deleteall` 删除指定行的所有单元，也可以传递一个时间戳参数，比如：
....
hbase> deleteall 'ns1:t1', 'r1'
hbase> deleteall 't1', 'r1'
hbase> deleteall 't1', 'r1', 'c1'
hbase> deleteall 't1', 'r1', 'c1', ts1
hbase> deleteall 't1', 'r1', 'c1', ts1, {VISIBILITY=>'PRIVATE|SECRET'}
....

=== get ===

获得行或单元格内容；接受表名、行以及可选的包含列、时间戳、时间范围的字典参数。例子如下：

....
hbase> get 'ns1:t1', 'r1'
hbase> get 't1', 'r1'
hbase> get 't1', 'r1', {TIMERANGE => [ts1, ts2]}
hbase> get 't1', 'r1', {COLUMN => 'c1'}
hbase> get 't1', 'r1', {COLUMN => ['c1', 'c2', 'c3']}
hbase> get 't1', 'r1', {COLUMN => 'c1', TIMESTAMP => ts1}
hbase> get 't1', 'r1', {COLUMN => 'c1', TIMERANGE => [ts1, ts2], VERSIONS => 4}
hbase> get 't1', 'r1', {COLUMN => 'c1', TIMESTAMP => ts1, VERSIONS => 4}
hbase> get 't1', 'r1', {FILTER => "ValueFilter(=, 'binary:abc')"}
hbase> get 't1', 'r1', 'c1'
hbase> get 't1', 'r1', 'c1', 'c2'
hbase> get 't1', 'r1', ['c1', 'c2']
hbase> get 't1', 'r1', {COLUMN => 'c1', ATTRIBUTES => {'mykey'=>'myvalue'}}
hbase> get 't1', 'r1', {COLUMN => 'c1', AUTHORIZATIONS => ['PRIVATE','SECRET']}
hbase> get 't1', 'r1', {CONSISTENCY => 'TIMELINE'}
hbase> get 't1', 'r1', {CONSISTENCY => 'TIMELINE', REGION_REPLICA_ID => 1}
....

=== put ===

将值填入到<表，行，列>指定的单元格中，同时可以指定时间戳。

....
hbase> put 'ns1:t1', 'r1', 'c1', 'value'  // <1>
hbase> put 't1', 'r1', 'c1', 'value'			// <1>
hbase> put 't1', 'r1', 'c1', 'value', ts1 // <2>
hbase> put 't1', 'r1', 'c1', 'value', {ATTRIBUTES=>{'mykey'=>'myvalue'}}  // <3>
hbase> put 't1', 'r1', 'c1', 'value', ts1, {ATTRIBUTES=>{'mykey'=>'myvalue'}}  // <3>
hbase> put 't1', 'r1', 'c1', 'value', ts1, {VISIBILITY=>'PRIVATE|SECRET'}   // <3>
....

<1> 把 'value' 填入到表为't1'，行键为'r1'，列为'c1' 指定的单元格中
<2> 同 <1> ，只是显示的指定该单元格值的时间戳为 ts1
<3> 通 <1> 和 <2> ，在添加额外的属性

=== scan ===

扫描指定的表，批量获取表中的数据。表名作为必选参数，可选参数为扫描器规范。
扫描器规范可以包括以下参数中的一个或多个：

* TIMERANGE
* FILTER
* LIMIT
* STARTROW
* STOPROW
* ROWPREFIXFILTER
* TIMESTAMP
* MAXLENGTH
* COLUMNS
* CACHE
* RAW
* VERSIONS

如果没有指定列，则会扫描所有的列。

过滤器可以使用两种方式来指定：

1. 使用一个过滤字符串
2. 使用过滤的JAVA包名

以下是 `scan` 的一些例子：

....
hbase> scan 'hbase:meta'
hbase> scan 'hbase:meta', {COLUMNS => 'info:regioninfo'}
hbase> scan 'ns1:t1', {COLUMNS => ['c1', 'c2'], LIMIT => 10, STARTROW => 'xyz'}
hbase> scan 't1', {COLUMNS => ['c1', 'c2'], LIMIT => 10, STARTROW => 'xyz'}
hbase> scan 't1', {COLUMNS => 'c1', TIMERANGE => [1303668804, 1303668904]}
hbase> scan 't1', {REVERSED => true}
hbase> scan 't1', {ROWPREFIXFILTER => 'row2', FILTER => "
  (QualifierFilter (>=, 'binary:xyz')) AND (TimestampsFilter ( 123, 456))"}
hbase> scan 't1', {FILTER =>
  org.apache.hadoop.hbase.filter.ColumnPaginationFilter.new(1, 0)}
hbase> scan 't1', {CONSISTENCY => 'TIMELINE'}
For setting the Operation Attributes
hbase> scan 't1', { COLUMNS => ['c1', 'c2'], ATTRIBUTES => {'mykey' => 'myvalue'}}
hbase> scan 't1', { COLUMNS => ['c1', 'c2'], AUTHORIZATIONS => ['PRIVATE','SECRET']}
hbase> scan 't1', {COLUMNS => ['c1', 'c2'], CACHE_BLOCKS => false} // <1>
hbase> scan 't1', {RAW => true, VERSIONS => 10}  // <2>
....

<1> 这里有一个高级附加选项 -- CACHE_BLOCKS -- 用来指定块缓存是打开(如果设置为true) 还是关闭(如果设置为false)
<2> RAW 也是一个高级选项，用来指示扫描器是否返回所有的单元格（包括标记为删除和未收集已删除单元格）。该选项不能和 COLUMNS 联合使用。默认该参数为 false

=== truncate 和 truncate_preserve ===

truncate 类似 delete, 但该命令会立即删除表中所有的数据以及region的划分. 它的内 部实现是将指定的表下线, 删除, 并重建. 如果只想立即删除表中所有的数据而不想丢掉原来 的region划分, 需要使用 truncate_preserve。


=== get_counter ===

根据指定的<表，行，列>统计单元格数量

....
hbase> get_counter 'ns1:t1', 'r1', 'c1'
hbase> get_counter 't1', 'r1', 'c1
....

== 命名空间管理命令 ==

这部分命令可以通过运行 `help 'namespace'` 来获得相关帮助

=== alter_namespace ===

更改命名空间属性，包括增加和删除。

....
hbase> alter_namespace 'ns1', {METHOD => 'set', 'PROERTY_NAME' => 'PROPERTY_VALUE'}
hbase> alter_namespace 'ns1', {METHOD => 'unset', NAME=>'PROERTY_NAME'}
....

=== create_namespace ===

创建命名空间

....
hbase> create_namespace 'ns1'
hbase> create_namespace 'ns1', {'PROERTY_NAME'=>'PROPERTY_VALUE'}
....

=== describe_namespace ===

描述命名空间

`hbase> describe_namespace 'ns1'`

=== drop_namespace ===

删除指定的namespace。要删除的namespace必须是一个空的namespace，不能存在表。

`hbase> drop_namespace '<namespace>'`

=== list_namespace ===

列出HBase中所有的namespace，可以加上正则表达式<regex>来对结果进行匹配

`hbase>list_namespace ['<regex>']`



[[hbase.shell.noninteractive]]
== 在系统脚本中使用HBase Shell ==

可以在操作系统的shell里（比如Bash）很方便的利用HBase shell来和HBase进行交互。以下的例子均已Bash作为系统脚本样例，但做响应的语法调整后，对C风格的shell--比如csh/tcsh--也是适用的。


NOTE: 以这种方式调用HBase Shell命令比较慢，因此在编写这类脚本时要有这个意识。

.传递命令给 HBase Shell
====
你可以使用 `echo` 命令和 `|` 管道操作符方式给HBase Shell 传递参数，从而实现非交互模式。
确保要传递给HBase Shell的命令已经经过了转移，否则会被shell解释。

[source,bash]
----
$ echo "describe 'test1'" | hbase shell -n

Version 1.1.2.2.4.0.0-169, r61dfb2b344f424a11f93b3f086eab815c1eb0b6a, Wed Feb 10 07:08:51 UTC 2016

describe 'test1'

DESCRIPTION                                          ENABLED
 'test1', {NAME => 'cf', DATA_BLOCK_ENCODING => 'NON true
 E', BLOOMFILTER => 'ROW', REPLICATION_SCOPE => '0',
  VERSIONS => '1', COMPRESSION => 'NONE', MIN_VERSIO
 NS => '0', TTL => 'FOREVER', KEEP_DELETED_CELLS =>
 'false', BLOCKSIZE => '65536', IN_MEMORY => 'false'
 , BLOCKCACHE => 'true'}
1 row(s) in 3.2410 seconds
----

为了抑制所有输出，可以将其重定向到  _/dev/null:_

[source,bash]
----
$ echo "describe 'test'" | hbase shell -n > /dev/null 2>&1
----
====

.检查脚本运行结果
====
因为脚本并不是设计用来做交互操作的，因此你需要一种方法来检测命令是运行成功还是失败。
HBase shell 使用标准返回码来表示命令执行状态。即 `0` 表示成功, 非0表示失败。
我们可以通过 `$?` 来获得上个命令的执行状态，通过这种方式就能知道HBase Shell
命令执行成功与否了。


[source,bash]
----
#!/bin/bash

echo "describe 'test'" | hbase shell -n > /dev/null 2>&1
status=$?
echo "The status was " $status
if ($status == 0); then
    echo "The command succeeded"
else
    echo "The command may have failed."
fi
return $status
----
====

=== 脚本内检查执行成功与失败 ===
获得一个命令的返回码为 `0` 意味着命令完全执行成功。但是获得一个非0值并不意味着命令一定都是失败的。也许命令已经制定成功了，但是因为客户端丢失连接，或者其他异常情况发生。这是因为RPC命令是无状态的。

唯一确定操作的状态是做一个检测。比如，如果你的脚本是创建一个表，但是返回了非0值。那么在你重新创建该表之前应该检查该表是否已经存在。


== 从一个命令文件中读取 HBase Shell 命令

你可以把一系列 HBase Shell 命令写入到一个文件中，每行一个命令。然后把该文件传递给 HBase Shell。

.命令文件样例
====
----
create 'test', 'cf'
list 'test'
put 'test', 'row1', 'cf:a', 'value1'
put 'test', 'row2', 'cf:b', 'value2'
put 'test', 'row3', 'cf:c', 'value3'
put 'test', 'row4', 'cf:d', 'value4'
scan 'test'
get 'test', 'row1'
disable 'test'
enable 'test'
----
====

.指挥 HBase Shell 执行命令
====
把命令文件当做一个参数传递给 `hbase shell` 命令后，每个命令被执行，然后输出结果。
如果命令文件里，没有 `exit` 命令，那么执行完毕后，你会得到一个HBase Shell 提示符而不是退出。

这里没有办法通过程序的方式来检查每个独立的命令执行结果是成功还是失败。人虽然可以通过屏幕的输出来检查执行结果，但是命令以及脚本本身是无法做到这点。

[source,bash]
----
$ ./hbase shell ./sample_commands.txt
0 row(s) in 3.4170 seconds

TABLE
test
1 row(s) in 0.0590 seconds

0 row(s) in 0.1540 seconds

0 row(s) in 0.0080 seconds

0 row(s) in 0.0060 seconds

0 row(s) in 0.0060 seconds

ROW                   COLUMN+CELL
 row1                 column=cf:a, timestamp=1407130286968, value=value1
 row2                 column=cf:b, timestamp=1407130286997, value=value2
 row3                 column=cf:c, timestamp=1407130287007, value=value3
 row4                 column=cf:d, timestamp=1407130287015, value=value4
4 row(s) in 0.0420 seconds

COLUMN                CELL
 cf:a                 timestamp=1407130286968, value=value1
1 row(s) in 0.0110 seconds

0 row(s) in 1.5630 seconds

0 row(s) in 0.4360 seconds
----
====

== 传递 VM 选项给 Shell

你可以使用 `HBASE_SHELL_OPTS` 环境变量来传递 VM 选项给 HBase Shell。可以直接在命令行设置该环境变量，也可以写入到  _~/.bashrc_。

[source,bash]
----
$ HBASE_SHELL_OPTS="-verbose:gc -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps \
  -XX:+PrintGCDetails -Xloggc:$HBASE_HOME/logs/gc-hbase.log" ./bin/hbase shell
----

== Shell 技巧 ==

=== 从日志数据里抽取时间戳 ===

从hbase日志的 '08/08/16 20:56:29' 日期字符串转为时间戳，可以这样做：

----
hbase(main):021:0> import java.text.SimpleDateFormat
hbase(main):022:0> import java.text.ParsePosition
hbase(main):023:0> SimpleDateFormat.new("yy/MM/dd HH:mm:ss").parse("08/08/16 20:56:29", ParsePosition.new(0)).getTime() => 1218920189000
----

反过来是这样做：

----
hbase(main):021:0> import java.util.Date
hbase(main):022:0> Date.new(1218920189000).toString() => "Sat Aug 16 20:56:29 UTC 2008"
----

日期格式可以参考 link:http://download.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html[SimpleDateFormat].

[[tricks.pre-split]]
=== 预先分表 ===
通过HBase Shell 的 `create` 命令创建表时，可以有多种方式来预先分表。

最简单的方法是创建表时指定一个包含分割点的数组。注意，当你指定一个字符串作为分割点时，实际上会创建一系列字符串所表达的字节的分割点。比如指定一个 '10' 的分隔点，实际上指定 '\x31\30' 作为分割点。

当 `n` 作为分隔点数字时，表将会被分割 `n+1` 个区域。最低的区域包括最小的可能key到第一个分割点（但不包括）的key。
第二个区域则包含第一个分割点的key到第二个分隔点（但不包含）的可以。
以此类推，知道最后一个区域包括最后一个分割点的key到最大的key。


[source]
----
hbase>create 't1','f',SPLITS => ['10','20',30']
----

在上面例子中，表 't1' 有一个列族 'f',预先分割成4个区域。第一个区域包括包含从 key 从 '\x00' 到 '\x30' 的所有数据。(因为 '\x31' 是 '1' 的ASCII码)。

你也可可以通过指定一个文件来设定分割点。就像下面这样：

[source]
----
hbase>create 't14','f',SPLITS_FILE=>'splits.txt'
----

另外一个方式是基于分割算法和预期的区域数量来自动计算分割点。
HBase 提供基于十六进制数分割和连续分隔算法。

[source]
----
# create table with four regions based on random bytes keys
hbase>create 't2','f1', { NUMREGIONS => 4 , SPLITALGO => 'UniformSplit' }

# create table with five regions based on hex keys
hbase>create 't3','f1', { NUMREGIONS => 5, SPLITALGO => 'HexStringSplit' }
----

HBase Shell是一个高效的Ruby环境，我们可以使用Ruby语言来编写分割算法。

[source]
----
# generate splits for long (Ruby fixnum) key range from start to end key
hbase(main):070:0> def gen_splits(start_key,end_key,num_regions)
hbase(main):071:1>   results=[]
hbase(main):072:1>   range=end_key-start_key
hbase(main):073:1>   incr=(range/num_regions).floor
hbase(main):074:1>   for i in 1 .. num_regions-1
hbase(main):075:2>     results.push([i*incr+start_key].pack("N"))
hbase(main):076:2>   end
hbase(main):077:1>   return results
hbase(main):078:1> end
hbase(main):079:0>
hbase(main):080:0> splits=gen_splits(1,2000000,10)
=> ["\000\003\r@", "\000\006\032\177", "\000\t'\276", "\000\f4\375", "\000\017B<", "\000\022O{", "\000\025\\\272", "\000\030i\371", "\000\ew8"]
hbase(main):081:0> create 'test_splits','f',SPLITS=>splits
0 row(s) in 0.2670 seconds

=> Hbase::Table - test_splits
----

注意 HBase Shell 命令 `truncate` 实际上是先drop表，然后使用默认选项来创建表，它会丢失任何分割点参数。
所以，如果你要清空一个预分割的表，那么你就必须先drop表，然后显式的指定预分割参数来重新创建表。

=== 调试（Debug）

==== HBase Shell 调试开关

你可以设置一个调试开关来看到更多的输出，比如用于异常出现时的堆栈跟踪。

[source]
----
hbase> debug <RETURN>
----

==== 日志 DEBUG 级别

为了以DEBUG级来记录shell的日志，可以使用 `-d` 参数来运行 HBase Shell 。

[source,bash]
----
$ ./bin/hbase shell -d
----
